# Generated by Django 3.0.7 on 2021-05-22 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('reg_approved', models.BooleanField(default=False)),
                ('membership_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('------', '------'), ('male', 'MALE'), ('female', 'FEMALE')], default='Select gender', max_length=100)),
                ('marital_status', models.CharField(choices=[('-------', '-------'), ('single', 'SINGLE'), ('married', 'MARRIED')], default='Select marital status', max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('nok_name', models.CharField(blank=True, max_length=150)),
                ('nok_address', models.CharField(blank=True, max_length=200)),
                ('nok_relationship', models.CharField(blank=True, max_length=100)),
                ('nok_occupation', models.CharField(blank=True, max_length=100)),
                ('nok_age', models.IntegerField(blank=True, default=0, help_text='not less than 18', null=True)),
                ('nok_phone', models.CharField(blank=True, max_length=100)),
                ('job_name', models.CharField(blank=True, max_length=200)),
                ('job_address', models.CharField(blank=True, max_length=200)),
                ('job_responsibility', models.CharField(blank=True, max_length=200)),
                ('job_post', models.CharField(blank=True, max_length=100)),
                ('ref_name1', models.CharField(blank=True, max_length=200)),
                ('ref_name2', models.CharField(blank=True, max_length=200)),
                ('ref_phone1', models.CharField(blank=True, max_length=100)),
                ('ref_phone2', models.CharField(blank=True, max_length=100)),
                ('ref_id1', models.CharField(blank=True, max_length=100)),
                ('ref_id2', models.CharField(blank=True, max_length=100)),
                ('form_receipt', models.ImageField(blank=True, max_length=255, upload_to=users.models.upload_directory_path)),
                ('applicant_photo', models.ImageField(blank=True, max_length=255, upload_to=users.models.upload_directory_path)),
                ('applicant_id', models.ImageField(blank=True, max_length=255, upload_to=users.models.upload_directory_path)),
                ('nok_photo', models.ImageField(blank=True, max_length=255, upload_to=users.models.upload_directory_path)),
                ('nok_id', models.ImageField(blank=True, max_length=255, upload_to=users.models.upload_directory_path)),
                ('hometown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hometown', to='users.Lga')),
                ('lg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lg', to='users.Lga')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='users.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.State'),
        ),
    ]
