# Generated by Django 3.0.7 on 2021-05-23 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRegistrationReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(max_length=255, upload_to='reg_receipt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_reg_receipt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
