# Generated by Django 3.0.7 on 2021-05-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadregistrationreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reg_receipt',
            field=models.ImageField(default='', max_length=255, upload_to='reg_receipt'),
            preserve_default=False,
        ),
    ]
