# Generated by Django 3.0.7 on 2021-05-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_reg_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadRegistrationReceipt',
        ),
    ]
