# Generated by Django 3.0.7 on 2021-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_uploadregistrationreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('------', '---SELECT RELIGION---'), ('islam', 'ISLAM'), ('christianity', 'CHRISTIANITY'), ('others', 'OTHERS')], default='Select religion', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('------', '---SELECT GENDER---'), ('male', 'MALE'), ('female', 'FEMALE')], default='Select gender', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('-------', '---SELECT MARITAL STATUS---'), ('single', 'SINGLE'), ('married', 'MARRIED')], default='Select marital status', max_length=100),
        ),
    ]
